version: "3"
services:
  nutmeg-slackbot:
    container_name: nsb
    build: ./slackbot
    env_file:
      - env/prd.env
    volumes:
      - ./slackbot:/work
    ports:
      - 3000:3000
    tty: true
    command: 'python main.py'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo:/data/configdb

  api:
    container_name: 'api'
    build:
      context: ./api
    volumes:
      - ./api:/go/src/work
    ports:
      - '1323:1323'
    command: './start.sh'
    depends_on:
      - mongo

  vite-view:
    build:
      context: ./vite
    working_dir: /app
    volumes:
      - ./vite:/app
    command: 'npm run dev'
    ports:
      - '3001:3001'
    tty: true
    stdin_open: true
    environment:
      - vite/.env
